ctf_puck:
    image: puckkid/ctf:base
    volumes:
        - ./share:/home/ctf_puck:ro
        - ./xinetd:/etc/xinetd.d/ctf_puck:ro
    ports:
        - "20001:9999"
    expose:
        - "9999"
    restart: "always"
